services:
  vaultwarden:
    image: ghcr.io/dani-garcia/vaultwarden:latest
    container_name: vaultwarden
    restart: always
    volumes:
      - ${CONFIG_ROOT:-.}/vaultwarden/vw-data:/data
    env_file:
      - path: ${CONFIG_ROOT:-.}/vaultwarden/.env
        required: false
    environment:
      - DOMAIN=https://vaultwarden.${TAILNET_DOMAIN}
    depends_on:
      stack-bootstrap:
        condition: service_completed_successfully
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=vaultwarden
      - tsdproxy.port.1=443/https:80/http
      - tsdproxy.dash.label=Vaultwarden
    profiles:
      - vaultwarden

  vaultwarden-backup:
    image: ghcr.io/adrienpoupa/rclone-backup:latest
    container_name: vaultwarden-backup
    restart: always
    env_file:
      - path: ${CONFIG_ROOT:-.}/vaultwarden/backup.env
        required: false
    depends_on:
      stack-bootstrap:
        condition: service_completed_successfully
    environment:
      - BACKUP_FOLDER_NAME_1=attachments
      - BACKUP_FOLDER_PATH_1=/vw-data/attachments
      - BACKUP_FOLDER_NAME_2=sends
      - BACKUP_FOLDER_PATH_2=/vw-data/sends
      - BACKUP_FOLDER_NAME_3=rsa-key
      - BACKUP_FOLDER_PATH_3=/vw-data/rsa_key
      - DB_TYPE=sqlite
      - SQLITE_DATABASE=/vw-data/db.sqlite3
    volumes:
      - ${CONFIG_ROOT:-.}/vaultwarden/vw-data:/vw-data
      - ${CONFIG_ROOT:-.}/vaultwarden/backup:/config
    profiles:
      - vaultwarden-backup
