services:
  tandoor:
    image: ghcr.io/tandoorrecipes/recipes:latest
    container_name: tandoor
    restart: always
    env_file:
      - path: ${CONFIG_ROOT:-.}/tandoor/.env
        required: false
    depends_on:
      stack-bootstrap:
        condition: service_completed_successfully
    volumes:
      - ${CONFIG_ROOT:-.}/tandoor/database:/opt/recipes/database
      - ${CONFIG_ROOT:-.}/tandoor/mediafiles:/opt/recipes/mediafiles
      - tandoor-staticfiles:/opt/recipes/staticfiles
    healthcheck:
      test: ["CMD", "wget", "http://127.0.0.1:80/", "-qO", "/dev/null"]
      interval: 1m
      retries: 10
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=tandoor
      - tsdproxy.port.1=${TSDPROXY_ACCESS_MODE:-443/https}:80/http
      - tsdproxy.dash.label=Tandoor
    profiles:
      - tandoor

  tandoor-backup:
    image: ghcr.io/adrienpoupa/rclone-backup:latest
    container_name: tandoor-backup
    restart: always
    env_file:
      - path: ${CONFIG_ROOT:-.}/tandoor/backup.env
        required: false
    depends_on:
      stack-bootstrap:
        condition: service_completed_successfully
    environment:
      - BACKUP_FOLDER_NAME=mediafiles
      - BACKUP_FOLDER_PATH=/data/mediafiles
      - DB_TYPE=sqlite
      - SQLITE_DATABASE=/database/recipes.db
    volumes:
      - ${CONFIG_ROOT:-.}/tandoor/database:/database
      - ${CONFIG_ROOT:-.}/tandoor/mediafiles:/data/mediafiles
      - ${CONFIG_ROOT:-.}/tandoor/backup:/config
    profiles:
      - tandoor-backup

volumes:
  tandoor-staticfiles:
